FROM ubuntu:22.04

RUN apt-get update && apt install -y nginx vim
RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf
RUN chown -R www-data:www-data /var/lib/nginx

COPY ./lion_app/lion_app/django.nginx /etc/nginx/sites-available/django
RUN ln -s /etc/nginx/sites-available/django /etc/nginx/sites-enabled/django

WORKDIR /etc/nginx

CMD ["nginx"]

RUN rm /etc/nginx/sites-enabled/default

EXPOSE 80
EXPOSE 443