version: "3"

services:
  lion-app:
    container_name: lion-app-dc
    image: limeskin.kr.ncr.ntruss.com/lion-app:latest
    ports:
      - "8000:8000"
    volumes:
      - ~/.aws:/root/.aws:ro
      - "staticfiles:/var/www/html/static"
    command:
      - "/start"
    depends_on:
      - db
    env_file:
      - ./.envs/prod/db
      - ./.envs/prod/django
      - ./.envs/prod/server
    environment:
      - AWS_SECRET_NAME=like/lion/prod

  nginx:
    container_name: lion-nginx-dc
    build:
      context: .
      dockerfile: dockerfile.nginx
    image: lion-nginx
    ports:
      - "8888:80"
    volumes:
      - "staticfiles:/var/www/html/static"
    env_file:
      - ./.envs/prod/server
    depends_on:
      - lion-app

  db:
    container_name: lion-postgres
    image: postgres:15
    env_file:
      - ./.envs/prod/db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  staticfiles:
  postgres_data:
