version: "3"

services:
  lion-app:
    container_name: lion-app-dc
    build:
      context: lion_app
      dockerfile: dockerfile
    image: lion-app
    ports:
      - "8000:8000"
    volumes:
      - lion-app:/var/www/html
      - ./lion_app:/app
    command:
      - "/start"
    env_file:
      - ./.envs/prod/db
      - ./.envs/prod/django
      - ./.envs/prod/server

  nginx:
    container_name: lion-nginx-dc
    build:
      context: .
      dockerfile: dockerfile.nginx
    image: lion-nginx
    ports:
      - "8888:80"
    volumes:
      - lion-app:/var/www/html
    depends_on:
      - lion-app

volumes:
  lion-app:
