name: lesson1

on:
  pull_request:
  push:

jobs:
  echo-event:
    name: echo event
    runs-on: ubuntu-latest
    steps:
      - name: echo event
        # run: echo "This event is ${{ github.event_name }}"
        run: echo "This event is $GITHUB_EVENT_NAME"

      - name: echo github context
        run: echo "github url ${{ github.repositoryUrl }}"
      - name: list files
        run: ls -al

  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: docker build and export
        uses: docker/build-push-action@v4
        with:
          context: lion_app
          tags: lion-app:latest
          outputs: type=docker,dest=/tmp/lion-app.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lion-app
          path: /tmp/lion-app.tar

  docker-images:
    name: docker images
    if: ${{ always() }}
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: lion-app
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/lion-app.tar
      - name: docker images
        run: docker images lion-app
