name: lesson1

on:
  pull_request:
  push:

jobs:
  echo-event:
    name: echo event
    runs-on: ubuntu-latest
    steps:
      - name: echo event
        # run: echo "This event is ${{ github.event_name }}"
        run: echo "This event is $GITHUB_EVENT_NAME"

      - name: echo github context
        run: echo "github url ${{ github.repositoryUrl }}"
      - name: list files
        run: ls -al

  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker compose build
        run: docker compose build lion-app
      - name: build
        working-directory: ./lion-app
        run: docker build -t lion-app
      - name: docker image
        run: docker images lion-app

  docker-images:
    name: docker images
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: docker images
        run: docker images lion-app
