name: release

on:
  release:
    types: [published]

env:
  IMAGE: ${{ vars.NCR_REGISTRY }}/lion-app
  IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/lion-app:latest

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.NCR_REGISTRY }}
          username: ${{ secrets.NCR_ACCESS_KEY_ID }}
          password: ${{ secrets.NCR_SECRET_KEY }}

      - name: Get release version
        id: get_release_version
        run: |
          echo "tag_version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: lion_app
          tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.get_release_version.outputs.tag_version }}"
          push: true
