name: release

on:
  release:
    types: [published]

env:
  IMAGE: ${{ vars.NCR_REGISTRY }}/lion-app
  IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/lion-app:latest

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.NCR_REGISTRY }}
          username: ${{ secrets.NCR_ACCESS_KEY_ID }}
          password: ${{ secrets.NCR_SECRET_KEY }}

      - name: Get release version
        id: get_release_version
        run: |
          echo "tag_version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: lion_app
          tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.get_release_version.outputs.tag_version }}"
          push: true
    outputs:
      tag_version: ${{ steps.get_release_version.outputs.tag_version }}

  deploy:
    name: Deploy to chart
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: checkout from helm chart
        uses: actions/checkout@v2
        with:
          repository: YubinMoon/helm-chart
          token: ${{ secrets.HELM_TOKEN }}

      - name: update helm chart
        run: |
          cd lion
          sed -i "s/tag:.*/tag: ${{needs.build-and-push.outputs.tag_version}}/g" ./values.yaml
          cat ./values.yaml

      - name: commit and push
        run: |
          git config --global user.name "Actions"
          git config --global user.email "munu220@gmail.com"
          git add .
          git commit -m "update helm chart"
          git push origin master
