name: test

on: push

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: test ssh
        run: |
          sshpass \
          -p ${{ secrets.PASSWORD }} ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ./lion;ls -al"
