name: test

on: push

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: test ssh
        run: sshpass -vp ${{ secrets.PASSWORD }} ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "ls -al"
