name: test

on: push

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: test ssh
        run: |
          ssh-keyscan -t rsa {{ secrets.USERNAME }} >> ~/.ssh/known_hosts
          sshpass \
          -p ${{ secrets.PASSWORD }} ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
          "cd ./lion;git pull;docker compose -f docker-compos.prod.yml up -d --build"
