name: test

on: push

jobs:
  ssh:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test ssh
        run: |
          echo "test"
          mkdir .ssh
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          sshpass \
          -vp ${{ secrets.PASSWORD }} ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
          "cd ./lion;git pull;docker compose -f docker-compos.prod.yml up -d --build"
